name: Release pipeline

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_PROD_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project
        run: |
          pip install -r unit-requirements.txt

      - name: Deploy PROD-churn-model-train job [prod environment]
        run: |
          dbx deploy PROD-churn-model-train --environment=prod

      - name: Deploy PROD-churn-model-deployment job [prod environment]
        run: |
          dbx deploy PROD-churn-model-deployment --environment=prod

      - name: Deploy PROD-churn-model-inference-batch job [prod environment]
        run: |
          dbx deploy PROD-churn-model-inference-batch --environment=prod

      - name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@v4

        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: new ml model
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Release for version ${{ github.ref }}.
          draft: false
          prerelease: false