name: Release pipeline

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_PROD_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: setup.py

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Deploy PROD-telco-churn-model-train job [prod environment]
        run: |
          dbx deploy PROD-telco-churn-model-train --environment=prod

      - name: Deploy PROD-telco-churn-model-deployment job [prod environment]
        run: |
          dbx deploy PROD-telco-churn-model-deployment --environment=prod

      - name: Deploy PROD-telco-churn-model-inference-batch job [prod environment]
        run: |
          dbx deploy PROD-telco-churn-model-inference-batch --environment=prod

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Release for version ${{ github.ref }}.
          draft: false
          prerelease: false